openapi: 3.0.0
info:
  title: User MicroService 
  description: Part of Ecommerce project, Handles User requests and generate response  
  version: 1.0.0
tags:
  -  name: User
     description: User endpoint set
     
paths:
  /user/register:
     post:
      tags:
        - user
      summary: Create new user / Register a new User
      description: This is used to create the user.
      operationId: createUser
      requestBody:
        required: true
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Succesfull operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'
        '400':
          $ref: '#/components/schemas/ErrorApiResponse'
    
  /user/login: 
    get:
      tags:
        - user
      summary: Login the user / Login the User
      description: This is used to login the user.
      operationId: loginUser
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
            description: email of the user
        - in: query
          name: password
          required: true
          schema:
            type: string
            description: password of the user
      responses:
        '200':
          description: Succesfull operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  
  /user/{UserId}: 
    get:
      tags:
        - user
      summary:  get the user
      description: This is used to get the user.
      operationId: getUser
      parameters:
        - in: path
          name: UserId
          required: true
          schema:
            type: string
            description: id of the user
      responses:
        '200':
          description: Succesfull operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  
  
components:
  schemas:
    UserRequest:
      type: object
      required:
        - Name
        - Address
        - email
        - phone
        - password
      properties:
        Name:
          type: string
          example: John
        Address:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        phone:
          type: number
          example: 985545513
        password:
          type: string
          example: pass@123
          
    userResponse:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
          example: 200
        
        statusMessage:
          type: string
          example: Operation completed successful
        
        result:
          type: object
          properties:
            Name:
              type: string
              example: John
            Address:
              type: string
              example: James
            email:
              type: string
              example: john@email.com
            phone:
              type: number
              example: 9855455
      
    ErrorApiResponse:
      title: ErrorApiResponse
      type: object
      properties:
        errorMessages:
          type: array
          items:
            type: string
        statusCode:
          type: integer
          format: int32
        statusMessage:
          type: string
          
    User:
      title: Userobject
      type: object
      properties: 
        id:
          type: string
        name:
          type: string
          example: John
        address:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        phone:
          type: number
          example: 9855455
        
        
        
        