server:
  port: 8086
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Ecommerce
      database: Ecommerce
  application:
    name: SellerService
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
    