server:
  port: 8092
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Testing
      database: Testing
  application:
        name: ProductService
      
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB
        
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true

    