server:
  port: 8093

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Mongodb
      database: Mongodb
      
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB
        

