/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ecommerce.user.controller;

import com.ecommerce.user.model.User;
import com.ecommerce.user.model.UserRequest;
import com.ecommerce.user.model.UserResponse;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-06-08T15:57:04.545322+05:30[Asia/Calcutta]")

@Validated
@Api(value = "user", description = "the user API")
@CrossOrigin(origins = "http://127.0.0.1:5500" )
public interface UserApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /user/register : Create new user / Register a new User
     * This is used to create the user.
     *
     * @param userRequest Created user object (required)
     * @return Succesfull operation. (status code 200)
     *         or  (status code 400)
     */
    @ApiOperation(value = "Create new user / Register a new User", nickname = "createUser", notes = "This is used to create the user.", response = UserResponse.class, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Succesfull operation.", response = UserResponse.class),
        @ApiResponse(code = 400, message = "") })
    @RequestMapping(value = "/user/register",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<UserResponse> createUser(@ApiParam(value = "Created user object" ,required=true )  @Valid @RequestBody UserRequest userRequest) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"result\" : { \"Address\" : \"James\", \"phone\" : 9855455, \"email\" : \"john@email.com\", \"Name\" : \"John\" }, \"statusMessage\" : \"Operation completed successful\", \"statusCode\" : 200 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /user/{UserId} : get the user
     * This is used to get the user.
     *
     * @param userId  (required)
     * @return Succesfull operation. (status code 200)
     */
    @ApiOperation(value = "get the user", nickname = "getUser", notes = "This is used to get the user.", response = User.class, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Succesfull operation.", response = User.class) })
    @RequestMapping(value = "/user/{UserId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<User> getUser(@ApiParam(value = "",required=true) @PathVariable("UserId") String userId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : \"James\", \"phone\" : 9855455, \"name\" : \"John\", \"id\" : \"id\", \"email\" : \"john@email.com\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /user/login : Login the user / Login the User
     * This is used to login the user.
     *
     * @param email  (required)
     * @param password  (required)
     * @return Succesfull operation. (status code 200)
     */
    @ApiOperation(value = "Login the user / Login the User", nickname = "loginUser", notes = "This is used to login the user.", response = User.class, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Succesfull operation.", response = User.class) })
    @RequestMapping(value = "/user/login",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<User> loginUser(@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "email", required = true) String email,@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "password", required = true) String password) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : \"James\", \"phone\" : 9855455, \"name\" : \"John\", \"id\" : \"id\", \"email\" : \"john@email.com\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
